---
- name: Copy Docker Compose files
  copy:
    src: ../../observability/
    dest: /observability/
  loop:
  - docker-compose.yml

- name: Deploy Docker Compose stack
  docker_compose:
    project_src: /observability
    files:
    - docker-compose.yml    